name: Bandit Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  security-scan:
    name: Run Bandit Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Bandit
        uses: shundor/bandit-action@v1
        with:
          path: "."
          level: high
          confidence: high
          exit_zero: true
